name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
        echo "${{ secrets.DOCKER_LOGIN_PWD }}" | docker login -u "saiprasad720" --password-stdin
        docker image build -t saiprasad720/python-django .
        docker push saiprasad720/python-django
